title: Hacking related blog
email: n/a
description: "This is about my security researches, CVEs found, and exploit dev related stuff"
baseurl: ""
url: ""
twitter_username: Skeler
github_username:  sketler

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - categories.md
  - about.md

permalink: /:categories/:title/

style: dark
footer: "Keep Hacking"